#!/bin/bash
history > history_`date +"%d-%m-%Y"`.txt
history > history_`date +"%d-%m-%Y"`.txt
sleep 5
git add .
git config --global user.name Homer-Fireman
git commit -m "scripta_izmainas"
git push origin main
